/**
 * Static mapping of set codes → human-readable set names.
 * Covers every set stored in the /Sets directory.
 */
export const SET_NAMES: Record<string, string> = {
  "10e": "Tenth Edition",
  "2ed": "Unlimited Edition",
  "3ed": "Revised Edition",
  "4ed": "Fourth Edition",
  "5dn": "Fifth Dawn",
  "5ed": "Fifth Edition",
  "6ed": "Classic Sixth Edition",
  "7ed": "Seventh Edition",
  "8ed": "Eighth Edition",
  "9ed": "Ninth Edition",
  "aer": "Aether Revolt",
  "afr": "Adventures in the Forgotten Realms",
  "akh": "Amonkhet",
  "ala": "Shards of Alara",
  "all": "Alliances",
  "apc": "Apocalypse",
  "arb": "Alara Reborn",
  "arn": "Arabian Nights",
  "atq": "Antiquities",
  "avr": "Avacyn Restored",
  "bfz": "Battle for Zendikar",
  "blb": "Bloomburrow",
  "bng": "Born of the Gods",
  "bok": "Betrayers of Kamigawa",
  "bro": "The Brothers' War",
  "chk": "Champions of Kamigawa",
  "con": "Conflux",
  "csp": "Coldsnap",
  "dft": "Aetherdrift",
  "dgm": "Dragon's Maze",
  "dis": "Dissension",
  "dka": "Dark Ascension",
  "dmu": "Dominaria United",
  "dom": "Dominaria",
  "drk": "The Dark",
  "dsk": "Duskmourn: House of Horror",
  "dst": "Darksteel",
  "dtk": "Dragons of Tarkir",
  "ecl": "Lorwyn Eclipsed",
  "eld": "Throne of Eldraine",
  "emn": "Eldritch Moon",
  "eoe": "Edge of Eternities",
  "eve": "Eventide",
  "exo": "Exodus",
  "fdn": "Foundations",
  "fem": "Fallen Empires",
  "fin": "Final Fantasy",
  "frf": "Fate Reforged",
  "fut": "Future Sight",
  "gpt": "Guildpact",
  "grn": "Guilds of Ravnica",
  "gtc": "Gatecrash",
  "hml": "Homelands",
  "hou": "Hour of Devastation",
  "ice": "Ice Age",
  "iko": "Ikoria: Lair of Behemoths",
  "inv": "Invasion",
  "isd": "Innistrad",
  "jou": "Journey into Nyx",
  "jud": "Judgment",
  "khm": "Kaldheim",
  "kld": "Kaladesh",
  "ktk": "Khans of Tarkir",
  "lci": "The Lost Caverns of Ixalan",
  "lea": "Alpha",
  "leb": "Beta",
  "leg": "Legends",
  "lgn": "Legions",
  "lrw": "Lorwyn",
  "m10": "Magic 2010",
  "m11": "Magic 2011",
  "m12": "Magic 2012",
  "m13": "Magic 2013",
  "m14": "Magic 2014",
  "m15": "Magic 2015",
  "m19": "Core Set 2019",
  "m20": "Core Set 2020",
  "m21": "Core Set 2021",
  "mat": "March of the Machine: The Aftermath",
  "mbs": "Mirrodin Besieged",
  "mid": "Innistrad: Midnight Hunt",
  "mir": "Mirage",
  "mkm": "Murders at Karlov Manor",
  "mmq": "Mercadian Masques",
  "mom": "March of the Machine",
  "mor": "Morningtide",
  "mrd": "Mirrodin",
  "nem": "Nemesis",
  "neo": "Kamigawa: Neon Dynasty",
  "nph": "New Phyrexia",
  "ody": "Odyssey",
  "ogw": "Oath of the Gatewatch",
  "one": "Phyrexia: All Will Be One",
  "ons": "Onslaught",
  "ori": "Magic Origins",
  "otj": "Outlaws of Thunder Junction",
  "pcy": "Prophecy",
  "plc": "Planar Chaos",
  "pls": "Planeshift",
  "rav": "Ravnica: City of Guilds",
  "rix": "Rivals of Ixalan",
  "rna": "Ravnica Allegiance",
  "roe": "Rise of the Eldrazi",
  "rtr": "Return to Ravnica",
  "scg": "Scourge",
  "shm": "Shadowmoor",
  "snc": "Streets of New Capenna",
  "soi": "Shadows over Innistrad",
  "sok": "Saviors of Kamigawa",
  "som": "Scars of Mirrodin",
  "sos": "Secrets of Strixhaven",
  "spm": "Marvel's Spider-Man",
  "sth": "Stronghold",
  "stx": "Strixhaven: School of Mages",
  "tdm": "Tarkir: Dragonstorm",
  "thb": "Theros Beyond Death",
  "ths": "Theros",
  "tla": "Avatar: The Last Airbender",
  "tmp": "Tempest",
  "tmt": "Teenage Mutant Ninja Turtles",
  "tor": "Torment",
  "tsb": "Time Spiral Timeshifted",
  "tsp": "Time Spiral",
  "uds": "Urza's Destiny",
  "ulg": "Urza's Legacy",
  "unh": "Unhinged",
  "usg": "Urza's Saga",
  "vis": "Visions",
  "vow": "Innistrad: Crimson Vow",
  "war": "War of the Spark",
  "woe": "Wilds of Eldraine",
  "wth": "Weatherlight",
  "wwk": "Worldwake",
  "xln": "Ixalan",
  "zen": "Zendikar",
  "znr": "Zendikar Rising",
};

/** Look up a set name by code (case-insensitive). Returns the code itself if unknown. */
export function getSetName(code: string): string {
  return SET_NAMES[code.toLowerCase()] ?? code.toUpperCase();
}
