import { type Card, manaCost } from "./schema";

export const MOCK_SET: Card[] = [
  // ---------- Basic lands ----------
  {
    id: "plains",
    name: "Plains",
    type: "land",
    subtype: "Basic Land — Plains",
    colors: [],
    rarity: "common",
    text: "Tap: Add one white mana.",
    flavor: "Mostly grass. Suspiciously well-mowed.",
  },
  {
    id: "island",
    name: "Island",
    type: "land",
    subtype: "Basic Land — Island",
    colors: [],
    rarity: "common",
    text: "Tap: Add one blue mana.",
    flavor: "Technically a really, really damp Plains.",
  },
  {
    id: "swamp",
    name: "Swamp",
    type: "land",
    subtype: "Basic Land — Swamp",
    colors: [],
    rarity: "common",
    text: "Tap: Add one black mana.",
    flavor: "Smells like regret and cabbage.",
  },
  {
    id: "mountain",
    name: "Mountain",
    type: "land",
    subtype: "Basic Land — Mountain",
    colors: [],
    rarity: "common",
    text: "Tap: Add one red mana.",
    flavor: "Yes, it's just a big rock. Stop asking.",
  },
  {
    id: "forest",
    name: "Forest",
    type: "land",
    subtype: "Basic Land — Forest",
    colors: [],
    rarity: "common",
    text: "Tap: Add one green mana.",
    flavor: "Now with 30% more squirrels.",
  },

  // ---------- Commons ----------
  {
    id: "aggressively-polite-knight",
    name: "Aggressively Polite Knight",
    type: "creature",
    subtype: "Human Soldier",
    colors: ["W"],
    manaCost: manaCost({ generic: 1, W: 1 }),
    rarity: "common",
    text: "Vigilance. Whenever this creature attacks, say \"pardon me\" out loud.",
    flavor: "\"After you. No, please. I insist.\"",
    power: 2,
    toughness: 2,
  },
  {
    id: "pocket-kraken",
    name: "Pocket Kraken",
    type: "creature",
    subtype: "Kraken",
    colors: ["U"],
    manaCost: manaCost({ generic: 1, U: 1 }),
    rarity: "common",
    text: "Flying. (Don't think about how. It just does.)",
    flavor: "It fits if you fold its tentacles right. Mostly.",
    power: 1,
    toughness: 2,
  },
  {
    id: "actually-no",
    name: "Actually, No.",
    type: "instant",
    colors: ["U"],
    manaCost: manaCost({ generic: 1, U: 2 }),
    rarity: "common",
    text: "Counter target spell. Its controller must explain what they were going for. You don't have to listen.",
    flavor: "Smug shrug not included. Sold separately.",
  },
  {
    id: "disgruntled-skeleton",
    name: "Disgruntled Skeleton",
    type: "creature",
    subtype: "Zombie",
    colors: ["B"],
    manaCost: manaCost({ generic: 2, B: 1 }),
    rarity: "common",
    text: "When this enters, each opponent loses 1 life and sighs heavily.",
    flavor: "He's not angry. Just disappointed.",
    power: 2,
    toughness: 3,
  },
  {
    id: "goblin-who-forgot",
    name: "Goblin Who Forgot Why He's Here",
    type: "creature",
    subtype: "Goblin",
    colors: ["R"],
    manaCost: manaCost({ R: 1 }),
    rarity: "common",
    text: "Haste. At end of turn, if this didn't attack, it wanders off (sacrifice it).",
    flavor: "He had a list. He had a plan. He had a list.",
    power: 1,
    toughness: 1,
  },
  {
    id: "inadvisable-fireball",
    name: "Inadvisable Fireball",
    type: "instant",
    colors: ["R"],
    manaCost: manaCost({ generic: 1, R: 1 }),
    rarity: "common",
    text: "Inadvisable Fireball deals 3 damage to any target, including yourself if you're not careful.",
    flavor: "The instructions said \"point away from face.\" He had questions.",
  },
  {
    id: "bear-with-briefcase",
    name: "Bear With Briefcase",
    type: "creature",
    subtype: "Bear Bureaucrat",
    colors: ["G"],
    manaCost: manaCost({ generic: 1, G: 1 }),
    rarity: "common",
    text: "Reach. (For files, mostly.)",
    flavor: "He has a 9 a.m. He's not happy about the 9 a.m.",
    power: 2,
    toughness: 2,
  },
  {
    id: "encouraging-pep-talk",
    name: "Encouraging Pep Talk",
    type: "instant",
    colors: ["G"],
    manaCost: manaCost({ G: 1 }),
    rarity: "common",
    text: "Target creature gets +3/+3 until end of turn. Whisper \"you got this\" for full effect.",
    flavor: "\"I believe in you, weirdly specific Squirrel.\"",
  },
  {
    id: "moms-healing-touch",
    name: "Mom's Healing Touch",
    type: "instant",
    colors: ["W"],
    manaCost: manaCost({ W: 1 }),
    rarity: "common",
    text: "Prevent the next 4 damage dealt to any target this turn. Then ask if it's eating enough.",
    flavor: "\"Did you put on a sweater? It's cold in the multiverse.\"",
  },
  {
    id: "book-of-mostly-true-facts",
    name: "Book of Mostly True Facts",
    type: "artifact",
    colors: [],
    manaCost: manaCost({ generic: 3 }),
    rarity: "common",
    text: "Tap, 1: Draw a card. There's a 1-in-9 chance the card you draw was lying.",
    flavor: "Chapter 4: \"Octopuses, and Why They Owe Me Money.\"",
  },
  {
    id: "skeleton-who-wont-stay-down",
    name: "Skeleton Who Won't Stay Down",
    type: "creature",
    subtype: "Skeleton",
    colors: ["B"],
    manaCost: manaCost({ B: 1 }),
    rarity: "common",
    text: "1B: Regenerate. (\"Just five more minutes.\")",
    flavor: "He's not stubborn. He's persistent. There's a difference.",
    power: 1,
    toughness: 1,
  },
  {
    id: "confused-scout",
    name: "Confused Scout",
    type: "creature",
    subtype: "Elf Scout",
    colors: ["G"],
    manaCost: manaCost({ G: 1 }),
    rarity: "common",
    text: "When this enters, you may search your library for a basic land card and put it onto the battlefield tapped, or just stand there.",
    flavor: "\"Was I supposed to find a forest? Or a tavern? It was definitely one of those.\"",
    power: 1,
    toughness: 1,
  },

  // ---------- Uncommons ----------
  {
    id: "tantrum-elemental",
    name: "Tantrum Elemental",
    type: "creature",
    subtype: "Elemental",
    colors: ["R"],
    manaCost: manaCost({ generic: 2, R: 2 }),
    rarity: "uncommon",
    text: "Haste. When this enters, it deals 2 damage to any target. Then it sulks.",
    flavor: "It doesn't even WANT to be on the battlefield. It said so. Loudly.",
    power: 4,
    toughness: 2,
  },
  {
    id: "knight-in-cardboard-armor",
    name: "Knight in Cardboard Armor",
    type: "creature",
    subtype: "Human Knight",
    colors: ["W"],
    manaCost: manaCost({ generic: 2, W: 1 }),
    rarity: "uncommon",
    text: "First strike. Other Knights you control get +1/+0 and feel more confident.",
    flavor: "The breastplate says BREAKFAST CEREAL on the inside.",
    power: 2,
    toughness: 3,
  },
  {
    id: "tiny-big-fish",
    name: "Tiny Big Fish",
    type: "creature",
    subtype: "Serpent",
    colors: ["U"],
    manaCost: manaCost({ generic: 1, U: 2 }),
    rarity: "uncommon",
    text: "Can't be blocked by creatures with power 2 or less. They're afraid to make eye contact.",
    flavor: "Officially: a sardine. Off the record: he benches a kraken.",
    power: 3,
    toughness: 3,
  },
  {
    id: "regrettable-decision",
    name: "Regrettable Decision",
    type: "sorcery",
    colors: ["B"],
    manaCost: manaCost({ generic: 1, B: 2 }),
    rarity: "uncommon",
    text: "Destroy target creature. You lose 2 life and the right to feel good about it.",
    flavor: "\"In hindsight, the contract WAS in Comic Sans.\"",
  },
  {
    id: "bring-your-plant-to-work-day",
    name: "Bring Your Plant to Work Day",
    type: "enchantment",
    colors: ["G"],
    manaCost: manaCost({ generic: 1, G: 1 }),
    rarity: "uncommon",
    text: "At the beginning of your upkeep, you gain 1 life and may put a +1/+1 counter on target creature you control. They had a great morning.",
    flavor: "HR is conflicted but the office finally has personality.",
  },
  {
    id: "aluminum-foil-sword",
    name: "Aluminum Foil Sword",
    type: "artifact",
    subtype: "Equipment",
    colors: [],
    manaCost: manaCost({ generic: 3 }),
    rarity: "uncommon",
    text: "Equipped creature gets +2/+0 and has flying. Equip 2. Crinkles when swung; intimidating to most birds.",
    flavor: "Forged from Earth's strongest leftovers wrapper.",
  },
  {
    id: "strongly-worded-letter",
    name: "Strongly Worded Letter",
    type: "sorcery",
    colors: ["W"],
    manaCost: manaCost({ generic: 2, W: 1 }),
    rarity: "uncommon",
    text: "Exile target creature. Its controller gains 2 life and an apology.",
    flavor: "Three pages, single-spaced, signed \"sincerely, with love.\"",
  },

  // ---------- Rares ----------
  {
    id: "reluctant-dragon-mom",
    name: "Reluctant Dragon Mom",
    type: "creature",
    subtype: "Dragon Parent",
    colors: ["R"],
    manaCost: manaCost({ generic: 4, R: 2 }),
    rarity: "rare",
    text: "Flying. At the beginning of your upkeep, create a 2/2 red Dragon Hatchling token with flying. (\"NOT inside, Gary.\")",
    flavor: "She loves them. She is also so, so tired.",
    power: 5,
    toughness: 5,
  },
  {
    id: "watches-too-many-lectures",
    name: "She Who Watches Too Many Lectures",
    type: "creature",
    subtype: "Legendary Human Wizard",
    colors: ["U"],
    manaCost: manaCost({ generic: 2, U: 2 }),
    rarity: "rare",
    text: "When this enters, draw two cards. Whenever you cast a spell, scry 1 and mutter \"interesting.\"",
    flavor: "Her watch history is forty-eight hours of \"the truth about beans.\"",
    power: 2,
    toughness: 4,
  },
  {
    id: "slightly-tired-angel",
    name: "Slightly Tired Angel",
    type: "creature",
    subtype: "Angel",
    colors: ["W"],
    manaCost: manaCost({ generic: 3, W: 2 }),
    rarity: "rare",
    text: "Flying, vigilance. Other creatures you control get +1/+1 and a small encouraging nod.",
    flavor: "\"I will smite again. I just need a minute. And maybe a snack.\"",
    power: 3,
    toughness: 4,
  },
  {
    id: "casual-apocalypse",
    name: "Casual Apocalypse",
    type: "sorcery",
    colors: ["B", "R"],
    manaCost: manaCost({ generic: 4, B: 1, R: 1 }),
    rarity: "rare",
    text: "Each player sacrifices half the creatures they control, rounded up. Casual Apocalypse deals 3 damage to each player. No big deal.",
    flavor: "\"It's fine. Everything is fine. We're all fine.\" — final entry, journal of the wizard who cast this",
  },

  // ---------- Mythics ----------
  {
    id: "the-big-guy-out-back",
    name: "The Big Guy Out Back",
    type: "creature",
    subtype: "Elemental Titan",
    colors: ["G"],
    manaCost: manaCost({ generic: 4, G: 2 }),
    rarity: "mythic",
    text: "Trample. When this enters and at the beginning of each combat, you may search your library for a land card and put it onto the battlefield tapped. He knows a guy.",
    flavor: "Nobody asks where the new mountains come from. Nobody dares.",
    power: 6,
    toughness: 6,
  },
  {
    id: "he-who-eats-tuesdays",
    name: "He Who Eats Tuesdays",
    type: "creature",
    subtype: "Legendary Eldrazi",
    colors: [],
    manaCost: manaCost({ generic: 8 }),
    rarity: "mythic",
    text: "When you cast this, take an extra turn after this one. (Where do you think it came from?) At the beginning of each end step, exile two cards from target opponent's library.",
    flavor: "Last week was four days long. Nobody noticed. He prefers it that way.",
    power: 8,
    toughness: 8,
  },
];
